-- ============================================================
-- TudoAgora — schema base
-- Substitui: CPT `empresa` + CPT oculto de itens de cardápio +
--             WooCommerce (produto) + PMPro (níveis) + taxonomias
-- ============================================================

-- `with schema public` e explicito de proposito: 20260101000002_search.sql
-- chama public.unaccent() e usa similarity() dentro de funcoes com
-- search_path = public. Sem fixar o schema, o Postgres escolheria o primeiro
-- schema do search_path do executor -- no Supabase hospedado as extensoes
-- pre-existentes vivem em `extensions`, e o resultado dependeria de quem rodou.
create extension if not exists pg_trgm with schema public;
create extension if not exists unaccent with schema public;

-- ---------- ENUMS ----------

create type business_status as enum ('draft', 'pending', 'active', 'suspended');
create type fulfillment_mode as enum ('delivery', 'pickup');
create type order_fulfillment as enum ('delivery', 'pickup');
create type order_status as enum (
  'pending', 'confirmed', 'preparing', 'out_for_delivery',
  'ready_for_pickup', 'completed', 'cancelled'
);
create type payment_method as enum ('pix', 'cash', 'card_on_delivery', 'card_online');
create type payment_status as enum ('pending', 'paid', 'failed', 'refunded');
create type plan_period as enum ('month', 'year');
create type subscription_status as enum ('pending', 'active', 'past_due', 'cancelled', 'expired');
create type profile_role as enum ('customer', 'merchant', 'admin');
create type member_role as enum ('owner', 'manager');
create type quote_status as enum ('new', 'contacted', 'won', 'lost');

-- ---------- GEOGRAFIA ----------

create table public.cities (
  id         bigint generated by default as identity primary key,
  name       text not null,
  state      text not null,
  slug       text not null unique,
  timezone   text not null default 'America/Cuiaba',
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- Grupos da home (as 9 pílulas/imagens da seção CATEGORIAS)
create table public.groups (
  id         bigint generated by default as identity primary key,
  name       text not null,
  slug       text not null unique,
  image_url  text,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

-- Categorias de negócio (subdivide os grupos)
create table public.categories (
  id              bigint generated by default as identity primary key,
  name            text not null,
  slug            text not null unique,
  group_id        bigint references public.groups(id) on delete set null,
  -- categoria que aceita cardápio/pedido online
  is_order_capable boolean not null default false,
  sort_order      integer not null default 0,
  is_active       boolean not null default true
);

create index categories_group_idx on public.categories (group_id);

-- ---------- EMPRESAS ----------
-- unifica os 26 `empresa` (WP) + 17 serviços + 10 lojas (subdomínios)

create table public.businesses (
  id              bigint generated by default as identity primary key,
  city_id         bigint not null references public.cities(id) on delete restrict,
  name            text not null,
  slug            text not null,
  -- subdomínio próprio: masterfarma, metal, ricardocelular...
  custom_slug     text unique,

  description     text,
  logo_url        text,
  cover_url       text,

  phone           text,
  whatsapp        text,
  email           text,
  instagram       text,
  address         text,
  neighborhood    text,
  latitude        numeric(10, 7),
  longitude       numeric(10, 7),
  -- {"mon":[["08:00","12:00"]], ...} ou {"special":"24/7"}
  opening_hours   jsonb not null default '{}'::jsonb,

  fulfillment     fulfillment_mode[] not null default '{}',
  payment_methods text[] not null default '{}',
  pix_key         text,
  delivery_fee_cents bigint not null default 0 check (delivery_fee_cents >= 0),
  min_order_cents    bigint not null default 0 check (min_order_cents >= 0),

  -- Plano Executivo: solicita orçamento
  accepts_quote   boolean not null default false,

  status          business_status not null default 'draft',
  is_featured     boolean not null default false,
  featured_until  timestamptz,

  -- proveniência da migração
  source          text,
  legacy_wp_id    bigint,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  unique (city_id, slug),
  constraint businesses_custom_slug_format check (
    custom_slug is null or custom_slug ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'
  )
);

create index businesses_city_status_idx on public.businesses (city_id, status);
create index businesses_name_trgm_idx  on public.businesses using gin (name gin_trgm_ops);
create index businesses_custom_slug_idx on public.businesses (custom_slug);
create index businesses_featured_idx   on public.businesses (is_featured, featured_until);

-- N:N — substitui o `data-ta-groups` multi-label do HTML
create table public.business_categories (
  business_id bigint not null references public.businesses(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  is_primary  boolean not null default false,
  primary key (business_id, category_id)
);

create index business_categories_category_idx on public.business_categories (category_id);

-- ---------- CARDÁPIO ----------

-- Seções do cardápio — POR EMPRESA.
-- Uma pizzaria tem "Pizzas 01 Sabor", outra tem "Pizzas Tradicionais".
-- Não confundir com `categories` (diretório global, compartilhado entre empresas).
create table public.menu_categories (
  id          bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name        text not null,
  slug        text not null,
  sort_order  integer not null default 0,
  unique (business_id, slug),
  unique (business_id, name)
);

create index menu_categories_business_idx on public.menu_categories (business_id, sort_order);

create table public.products (
  id               bigint generated by default as identity primary key,
  business_id      bigint not null references public.businesses(id) on delete cascade,
  menu_category_id bigint references public.menu_categories(id) on delete set null,
  name             text not null,
  description      text,
  price_cents      bigint not null default 0 check (price_cents >= 0),
  image_url        text,
  is_available     boolean not null default true,
  sort_order       integer not null default 0,
  source           text,
  legacy_wp_id     bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index products_business_idx on public.products (business_id, sort_order);
create index products_menu_category_idx on public.products (menu_category_id);

-- Grupos de opção (Borda, Sabor, Tamanho) — substitui o `pizza-config` avulso
create table public.option_groups (
  id          bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name        text not null,
  min_select  integer not null default 0 check (min_select >= 0),
  max_select  integer not null default 1 check (max_select >= 0),
  is_required boolean not null default false,
  sort_order  integer not null default 0,
  unique (business_id, name)
);

create table public.option_values (
  id              bigint generated by default as identity primary key,
  option_group_id bigint not null references public.option_groups(id) on delete cascade,
  name            text not null,
  price_delta_cents bigint not null default 0,
  is_available    boolean not null default true,
  sort_order      integer not null default 0,
  unique (option_group_id, name)
);

-- ---------- PEDIDOS ----------

create table public.orders (
  id                bigint generated by default as identity primary key,
  -- código curto exibido ao cliente e ao lojista (ex.: TA-4F2K9)
  public_id         text not null unique,

  business_id       bigint not null references public.businesses(id) on delete restrict,
  customer_id       uuid references auth.users(id) on delete set null,
  customer_name     text not null,
  customer_phone    text not null,
  customer_email    text,

  fulfillment       order_fulfillment not null,
  address           text,
  address_notes     text,

  status            order_status not null default 'pending',
  payment_method    payment_method not null,
  payment_status    payment_status not null default 'pending',
  payment_provider  text,
  payment_reference text,

  subtotal_cents    bigint not null default 0 check (subtotal_cents >= 0),
  delivery_fee_cents bigint not null default 0 check (delivery_fee_cents >= 0),
  discount_cents    bigint not null default 0 check (discount_cents >= 0),
  total_cents       bigint not null default 0 check (total_cents >= 0),

  notes             text,
  cancellation_reason text,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  confirmed_at      timestamptz,
  completed_at      timestamptz,

  constraint orders_delivery_needs_address check (
    fulfillment <> 'delivery' or address is not null
  )
);

create index orders_business_status_idx on public.orders (business_id, status, created_at desc);
create index orders_customer_idx        on public.orders (customer_id, created_at desc);
create index orders_public_id_idx       on public.orders (public_id);

-- itens guardam SNAPSHOT de nome/preço — obrigatório para histórico e impressão
create table public.order_items (
  id               bigint generated by default as identity primary key,
  order_id         bigint not null references public.orders(id) on delete cascade,
  product_id       bigint references public.products(id) on delete set null,
  product_name     text not null,
  unit_price_cents bigint not null check (unit_price_cents >= 0),
  quantity         integer not null check (quantity > 0),
  notes            text
);

create index order_items_order_idx on public.order_items (order_id);

create table public.order_item_options (
  id                 bigint generated by default as identity primary key,
  order_item_id      bigint not null references public.order_items(id) on delete cascade,
  option_group_name  text not null,
  option_value_name  text not null,
  price_delta_cents  bigint not null default 0
);

create index order_item_options_item_idx on public.order_item_options (order_item_id);

-- ---------- COMERCIAL / PLANOS ----------

create table public.plans (
  id           bigint generated by default as identity primary key,
  name         text not null,
  slug         text not null unique,
  tagline      text,
  price_cents  bigint not null check (price_cents >= 0),
  period       plan_period not null default 'year',
  -- valor exibido como "R$ 79,90/mês" quando o cobrança é anual
  monthly_equivalent_cents bigint,
  features     jsonb not null default '[]'::jsonb,
  is_featured  boolean not null default false,
  sort_order   integer not null default 0,
  is_active    boolean not null default true
);

create table public.subscriptions (
  id                  bigint generated by default as identity primary key,
  business_id         bigint not null references public.businesses(id) on delete cascade,
  plan_id             bigint not null references public.plans(id) on delete restrict,
  status              subscription_status not null default 'pending',
  provider            text,
  provider_reference  text,
  started_at          timestamptz,
  current_period_end  timestamptz,
  cancelled_at        timestamptz,
  created_at          timestamptz not null default now()
);

create index subscriptions_business_idx on public.subscriptions (business_id, status);
create unique index subscriptions_one_active_per_business
  on public.subscriptions (business_id)
  where status in ('pending', 'active', 'past_due');

-- ---------- MARKETING ----------

create table public.banners (
  id           bigint generated by default as identity primary key,
  business_id  bigint references public.businesses(id) on delete cascade,
  title        text,
  image_url    text,
  link_url     text,
  -- 'hero' | 'discover' | 'highlights' | 'storefront'
  placement    text not null default 'hero',
  starts_at    timestamptz,
  ends_at      timestamptz,
  sort_order   integer not null default 0,
  is_active    boolean not null default true
);

create index banners_placement_idx on public.banners (placement, sort_order) where is_active;

create table public.offers (
  id                bigint generated by default as identity primary key,
  business_id       bigint not null references public.businesses(id) on delete cascade,
  title             text not null,
  description       text,
  image_url         text,
  -- preço promocional e preço "de" (riscado). Null = oferta sem preço.
  price_cents       bigint,
  compare_at_cents  bigint,
  link_url          text,
  starts_at         timestamptz,
  ends_at           timestamptz,
  sort_order        integer not null default 0,
  is_active         boolean not null default true
);

create index offers_business_idx on public.offers (business_id, sort_order);

create table public.coupons (
  id               bigint generated by default as identity primary key,
  business_id      bigint references public.businesses(id) on delete cascade,
  code             text not null,
  percent_off      integer check (percent_off between 1 and 100),
  amount_off_cents bigint check (amount_off_cents >= 0),
  min_order_cents  bigint not null default 0 check (min_order_cents >= 0),
  max_uses         integer,
  used_count       integer not null default 0,
  starts_at        timestamptz,
  ends_at          timestamptz,
  is_active        boolean not null default true,
  unique (business_id, code)
);

create table public.quote_requests (
  id            bigint generated by default as identity primary key,
  business_id   bigint not null references public.businesses(id) on delete cascade,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  message       text,
  items         jsonb,
  status        quote_status not null default 'new',
  created_at    timestamptz not null default now()
);

create index quote_requests_business_idx on public.quote_requests (business_id, created_at desc);

-- ---------- AUTH / PAPÉIS ----------

create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  full_name  text,
  phone      text,
  role       profile_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.business_members (
  business_id bigint not null references public.businesses(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  role        member_role not null default 'owner',
  created_at  timestamptz not null default now(),
  primary key (business_id, user_id)
);

create index business_members_user_idx on public.business_members (user_id);

-- ---------- TRIGGERS ----------

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['businesses', 'products', 'orders', 'profiles'] loop
    execute format(
      'create trigger set_updated_at before update on public.%I
       for each row execute function public.touch_updated_at()', t);
  end loop;
end;
$$;

-- novo usuário -> profile de customer
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
