-- ===========================================================================
-- Meio a meio
--
-- Pizza meio a meio NÃO é uma opção: é um segundo produto na mesma linha.
--
-- A primeira tentativa caberia no que já existe — criar linhas de
-- `option_values` chamadas "Calabresa", "Portuguesa"... — e ela é errada de
-- três maneiras que só aparecem em produção:
--
--   1. Preço. `placeOrder` precifica como `product.price_cents + delta`. Com
--      a Margherita (R$ 45) de base e Quatro Queijos (R$ 55) de segunda
--      metade, o servidor veria `45 + 0` e entregaria R$ 10 a menos. O
--      `price_delta_cents` não conserta: ele é estático por valor enquanto o
--      preço da base varia, então seria preciso um valor para cada par
--      (base × metade) — 5 pizzas dariam 20 linhas para manter.
--
--   2. Cozinha. `order_items.product_id` aponta para a pizza base e a metade
--      só sobreviveria como texto em `order_item_options`. O painel do lojista
--      mostraria "1× Pizza Margherita" com "2º Sabor: Quatro Queijos" soterrado
--      numa lista de opções. O comentário em `pedidos/page.tsx` já registra que
--      essa exata ambiguidade (tamanho/borda) foi corrigida trazendo as
--      opções para dentro do item; para sabores o problema é pior, porque o
--      sabor errado não é um ajuste de borda, é a pizza errada.
--
--   3. Catálogo duplicado. Espelhar o cardápio em `option_values` cria uma
--      segunda fonte de verdade: renomear uma pizza passa a ser dois lugares,
--      e o `unique (option_group_id, name)` faz a divergência aparecer como
--      erro de insert, não como bug silencioso.
--
-- Então a metade é um `products` de verdade, gravado em tabela própria:
-- `order_item_halves` carrega o id do produto, o snapshot do nome e o preço
-- cobrado. A cozinha lê "Margherita / Quatro Queijos" e o servidor sabe
-- recalcular tudo do zero.
--
-- `halves_count` no valor da opção é o gatilho: "2 Sabores" tem
-- `halves_count = 2` e obriga o cliente a escolher 2 metades. "1 Sabor" tem
-- `halves_count = 0` e não abre seletor nenhum — a pizza inteira. Isso
-- preserva o grupo que a empresa já criou em vez de inventar um conceito
-- paralelo.
--
-- Quem pode virar metade: produtos da MESMA seção e disponíveis, exceto o
-- próprio produto. Mesma seção é o proxy para "mesma choosable de tamanho" —
-- a constraint real (mesmo conjunto de grupos de opção) é conferida no
-- `placeOrder`, que é a fronteira de confiança; a vitrine só sugere.
-- ============================================================================

alter table public.option_values
  add column halves_count integer not null default 0
  check (halves_count between 0 and 3);

comment on column public.option_values.halves_count is
  'Quantidade de metades que este valor exige. 0 = pizza inteira, sem seletor.';

-- O snapshot espelha `order_items`: nome e preço congelados no momento do
-- pedido, porque renomear a pizza amanhã não pode reescrever o histórico nem
-- a impressão da cozinha.
create table public.order_item_halves (
  id             bigint generated by default as identity primary key,
  order_item_id  bigint not null references public.order_items(id) on delete cascade,
  product_id     bigint references public.products(id) on delete set null,
  product_name   text not null,
  price_cents    bigint not null check (price_cents >= 0),
  -- A ordem das metades importa: a 1ª é a metade esquerda, a 2ª a direita.
  position       integer not null check (position >= 0)
);

create index order_item_halves_item_idx on public.order_item_halves (order_item_id);

-- ---------- RLS ----------
--
-- Mesma forma da `order_item_options_read`: quem enxerga o pedido enxerga as
-- metades dele. Sem esta policy a tabela ficaria invisível até para o lojista.

alter table public.order_item_halves enable row level security;

create policy order_item_halves_read on public.order_item_halves
  for select using (
    exists (
      select 1
      from public.order_items oi
      join public.orders o on o.id = oi.order_id
      where oi.id = order_item_id
        and (o.customer_id = auth.uid() or public.manages_business(o.business_id))
    )
  );

-- Nenhuma policy de INSERT: a gravação é server-side, junto com o pedido.

do $$
declare
  t text;
begin
  foreach t in array array['order_item_halves'] loop
    execute format('revoke truncate, references on public.%I from anon, authenticated', t);
  end loop;
end $$;

-- ===========================================================================
-- A RPC precisa devolver `halves_count`, senão a vitrine não sabe quando abrir
-- o seletor. `create or replace` mantém a assinatura, então quem já chama
-- `get_business_menu` (a página pública, a vitrine e o `placeOrder`) não muda
-- de chamada — só passa a receber um campo novo.
-- ===========================================================================

create or replace function public.get_business_menu(p_business_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'business', (
      select jsonb_build_object(
        'id', b.id, 'name', b.name, 'slug', b.slug, 'custom_slug', b.custom_slug,
        'description', b.description, 'logo_url', b.logo_url, 'cover_url', b.cover_url,
        'whatsapp', b.whatsapp, 'phone', b.phone, 'address', b.address,
        'neighborhood', b.neighborhood, 'opening_hours', b.opening_hours,
        'fulfillment', b.fulfillment, 'payment_methods', b.payment_methods,
        'pix_key', b.pix_key, 'delivery_fee_cents', b.delivery_fee_cents,
        'min_order_cents', b.min_order_cents
      )
      from public.businesses b
      where b.id = p_business_id and b.status = 'active'
    ),
    'menu_categories', (
      select coalesce(jsonb_agg(
        jsonb_build_object(
          'id', mc.id, 'name', mc.name, 'slug', mc.slug,
          'description', mc.description, 'image_url', mc.image_url,
          'item_count', (select count(*) from public.products p2
                          where p2.menu_category_id = mc.id and p2.is_available)
        ) order by mc.sort_order, mc.name
      ), '[]'::jsonb)
      from public.menu_categories mc
      where mc.business_id = p_business_id and mc.is_active
    ),
    'items', (
      -- O cast para int é obrigatório: `->>` devolve text, e ordenar text
      -- colocaria o sort_order 10 antes do 2 a partir do 10º item. A coluna
      -- é NOT NULL, então o cast nunca estoura.
      select coalesce(jsonb_agg(item order by (item ->> 'sort_order')::int, item ->> 'name'), '[]'::jsonb)
      from (
        select jsonb_build_object(
          'id', p.id, 'name', p.name, 'description', p.description,
          'price_cents', p.price_cents, 'compare_at_cents', p.compare_at_cents,
          'image_url', p.image_url, 'is_featured', p.is_featured,
          'menu_category_id', mc.id, 'menu_category_slug', mc.slug,
          'menu_category_name', mc.name, 'sort_order', p.sort_order,
          'option_groups', (
            select coalesce(jsonb_agg(
              jsonb_build_object(
                'id', g.id, 'name', g.name,
                'min_select', g.min_select, 'max_select', g.max_select,
                'is_required', g.is_required,
                'values', (
                  select coalesce(jsonb_agg(
                    jsonb_build_object(
                      'id', v.id, 'name', v.name,
                      'price_delta_cents', v.price_delta_cents,
                      'halves_count', v.halves_count
                    ) order by v.sort_order, v.name
                  ), '[]'::jsonb)
                  from public.option_values v
                  where v.option_group_id = g.id and v.is_available
                )
              ) order by g.sort_order, g.name
            ), '[]'::jsonb)
            from public.option_groups g
            where g.business_id = p_business_id
              -- Só entra o grupo que o próprio produto elt.
              --
              -- Antes (0005) valia o inverso: produto sem nenhuma linha em
              -- product_option_groups herdava TODOS os grupos da empresa. Isso
              -- não tem como desligar -- uma Coca-Cola de 6 reais acabava
              -- exigindo "Tamanho: Grande" e "Molho: Pesto", porque não havia
              -- como dizer "este item não tem opção". O elenco virou
              -- obrigatório e o backfill acima grava o que a heranca entregava.
              and exists (
                select 1 from public.product_option_groups pog
                where pog.product_id = p.id and pog.option_group_id = g.id
              )
          )
        ) as item
        from public.products p
        left join public.menu_categories mc on mc.id = p.menu_category_id
        where p.business_id = p_business_id
          and p.is_available
          and (mc.id is null or mc.is_active)
      ) s
    )
  )
  where exists (select 1 from public.businesses b where b.id = p_business_id and b.status = 'active');
$$;
